server:
    port: 8031
spring:
    application:
        name: turbine
eureka:
    client:
        service-url:
            defaultZone: http://ming:19951224@localhost:8761/eureka/ #Eureka Server地址
    instance:
        prefer-ip-address: true
turbine:
    appConfig: user,feign
    clusterNameExpression: "'default'"