server:
    port: 8000

#权限管理
#security:
#  basic:
#    enabled: true         #开启基于Http basic的认证
#  user:
#    name: ming            #配置登陆的账号是 user
#    password: 19951224    #配置登陆的密码是 19951224    如果不设置这块内容账号是user

spring:
  application:
    name: user     #用于指定到Eureka Server上的应用名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1995
    type: com.alibaba.druid.pool.DruidDataSource
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


#添加注册
eureka:
    client:
      serviceUrl:
         #defaultZone: http://eureka-server:8761/eureka/   #mac环境
         defaultZone: http://ming:19951224@peer1:8761/eureka/ #Eureka Server服务中心地址，携带认证的账号和密码
         #defaultZone: http://ming:19951224@localhost:8761/eureka/ #Eureka Server服务中心地址，携带认证的账号和密码
      healthcheck:
          enabled: true
    instance:
      prefer-ip-address: true     #标识将自己的IP注册到Eureka Server,默认为false
      metadata-map:                  #自定义元数据， key和value可以自定义编写
         author:  Lee JunMing
         age: 22







