server:
  port: 8011

spring:
  application:
    name: feign     #用于指定到Eureka Server上的应用名称
  cloud:
    service-registry:
      auto-registration:
        enabled: true    #false关闭服务自动注册


info:
   app:
      name: spring-boot-actuator
      version: 1.0.0


#添加注册
#单节点和配置集群环境是一样，因为多个Eureka Server之间会数据会相互同步
# defaultZone: http://localhost:8761/eureka/ #Eureka Server服务中心地址
#集群环境
eureka:
  client:
    serviceUrl:
     #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/  注册中心集群这样配置
      defaultZone: http://ming:19951224@localhost:8761/eureka/ #Eureka Server服务中心地址
  instance:
    prefer-ip-address: true     #标识将自己的IP注册到Eureka Server,默认为false

feign:
  compression:
    #feign对请求和响应的压缩支持
    request:
      enabled:  true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled:  true
