server:
  port: 8011

spring:
  application:
    name: feign     #用于指定到Eureka Server上的应用名称
  cloud:
    service-registry:
      auto-registration:
        enabled: true    #false关闭服务自动注册
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

info:
   app:
      name: spring-boot-actuator
      version: 1.0.0

feign:
  hystrix:
    enabled: true
  client:
    config:
        #把user换成default为全局配置
      user:
        # 相当与Request.Options
        connectTimeout: 5000
        readTimeout:  5000
        #配置Feign的日志级别，相当于代码配置的Logger
        loggerLevel: full
        #Feign的错误解码器，相当于代码中的ErrorDecoder
        #errorDecoder: com.ljm.cloud.feign.config.MyErrorDecoder
        #配置重试
        #retryer:  com.ljm.cloud.feign.config.SimpleRetryer
        #配置拦截器
        #requestInterceptors:
         # - com.ljm.cloud.feign.config.FooRequestInterceptor
    #false表示java代码优先
    #default-to-properties: false
#添加注册
#单节点和配置集群环境是一样，因为多个Eureka Server之间会数据会相互同步
# defaultZone: http://localhost:8761/eureka/ #Eureka Server服务中心地址
#集群环境
eureka:
  client:
    serviceUrl:
     #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/  注册中心集群这样配置
      defaultZone: http://ming:19951224@localhost:8761/eureka/ #Eureka Server服务中心地址
  instance:
    prefer-ip-address: true     #标识将自己的IP注册到Eureka Server,默认为false
logging:
  level:
    com.ljm.cloud.feign.feign.UserFeignClient: DEBUG